version: "3.8"
services:
  httpd:
    image: iamalan10/image
    container_name: container1
    ports:
    - "80:80"
    volumes:
    - vlm:/usr/local/apache2/htdocs/
    networks:
    - net1
    restart: always

volumes:
  vlm:
networks:
  net1:
    driver: bridge
