global:
  scrape_interval: 5s
  external_labels:
    monitor: 'node'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['52.66.247.115:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['52.66.247.115:9100']
